import fs from "fs"; import path from "path"; import { execSync } from "child_process"; import { Project, EditPlan } from "./types"; import { RESOLUTION_MAP, STORAGE } from "./constants"; import { hasFilter } from "./ffmpegUtils";
export const checkFFmpegInstalled=()=>{ try{execSync("ffmpeg -version"); return true;}catch{return false;} };
export const prepareWorkingDirectory=(projectId:string)=>{ const d=path.resolve(STORAGE.temp,projectId); fs.mkdirSync(d,{recursive:true}); return d; };
export const cutClips=()=>{}; export const applySpeedChanges=()=>{}; export const applyCrop=()=>{}; export const applyResolution=()=>{}; export const applyMusicSegment=()=>{}; export const mixOriginalAudioWithMusic=()=>{}; export const applyCaptions=()=>{}; export const applyZoomEffect=()=>{}; export const applyShakeEffect=()=>{}; export const applyFlashTransitions=()=>{}; export const applyColorGrade=()=>{}; export const applyQualityEnhancement=()=>{}; export const exportMP4=()=>{};
export const cleanupTempFiles=(dir?:string)=>{ if(dir&&fs.existsSync(dir)) fs.rmSync(dir,{recursive:true,force:true}); };
export const renderEditWithFFmpeg=(project:Project,editPlan:EditPlan)=>{ const wd=prepareWorkingDirectory(project.id); const out=path.resolve(STORAGE.renders,`${project.id}.mp4`); const size=RESOLUTION_MAP[editPlan.format][editPlan.resolution]; const filters=[`scale=${size}`,"setsar=1"]; if(project.enhancementOptions.sharpen) filters.push("unsharp=5:5:1.0:5:5:0.0"); if(project.enhancementOptions.colorBoost) filters.push("eq=saturation=1.2:contrast=1.1"); if(project.enhancementOptions.denoise) filters.push("hqdn3d"); if(project.enhancementOptions.fpsBoost&&hasFilter("minterpolate")) filters.push("minterpolate=fps=60");
 const musicInput=project.uploadedMusicPath?`-stream_loop -1 -i \"${project.uploadedMusicPath}\"`:""; const audioMap=project.uploadedMusicPath?"-map 0:v:0 -map 1:a:0":"-map 0:v:0 -map 0:a?";
 const cmd=`ffmpeg -y -i \"${project.uploadedVideoPath}\" ${musicInput} -t ${editPlan.duration} -vf \"${filters.join(",")}\" ${audioMap} -c:v libx264 -c:a aac -shortest \"${out}\"`;
 execSync(cmd); cleanupTempFiles(wd); return out; };
